### ISSUE TITLE
Workout-Page CSS

### ISSUE THREAD

**Issue by renfunny** [renfunny/GitUp.Now#6]
Crate CSS file for the workout page

**Comment by osorioj88** [comment]
# Workout-Page CSS

## User Story
I want the workout page to be structured similar to the homepage
So that I can demonstrate the different available exercises

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the workout page 
THEN I see a six different workouts with navigation and details

**Comment by renfunny** [comment]
The workout page (now called Exercises) CSS has been finished
![image](https://user-images.githubusercontent.com/105825652/196785679-b47a90a7-eefe-4e22-9710-16c4d973d53c.png)
